### PR TITLE
Module/genbabel update

### PR DESCRIPTION
**Pull request by yeohjingwui**
Here are the updated files for the genbabel (which is the standardfile_generator) module. These files have passed the Black, Flake8 and the Travis CI. Please have a look and merge the pull request if everything is okay. Let me know if you have any comments. There were some warnings from the dependencies, where I will try to fix them soon.  Thank you!

### CODE REVIEW

**Comment by veghp** [comment]
Please remove these lines from .travis.yml

    - pip install dnaplotlib
    - pip install tellurium
    - pip install simplesbml
    - pip install biopython
    - pip install reportlab

And add these packages to `setup.py` (`install_requires=`), because they are needed for synbiopython, not just for the testing.

**Comment by veghp** [comment]
Please see this line (and import pytest) for an example on how to handle temporary testing files so they are not generated in the project directory: https://github.com/Global-Biofoundries-Alliance/SynBioPython/blob/master/synbiopython/lab_automation/tests/test_Picklist.py#L29

**Comment by veghp** [comment]
Perhaps use `os.path.join()` in line 6 and elsewhere, so that it works on all OSs:
https://github.com/yeohjingwui/SynBioPython/blob/module/standardfile_generator-update/synbiopython/genbabel/tests/test_gensbolconv.py#L6

Otherwise all tests pass and it looks good.

**Comment by yeohjingwui** [comment]
Thank you so much for the comments. I have made the changes accordingly.

**Pull request merged**
